//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _519
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Phone_number { get; set; }
        public string Sex { get; set; }
        public int ID { get; set; }
        public string Photo { get; set; }
    }
}
